[[repos]]
repo = "local"
hooks = [
  {
    id = "biome-check",
    name = "biome-check",
    language = "system",
    pass_filenames = false,
    files = { glob = [ "*.ts", "*.json" ] },
    entry = "bun check",
    priority = 10,
  },
  {
    id = "type-check",
    name = "type-check",
    language = "system",
    pass_filenames = false,
    files = { glob = [ "*.ts" ] },
    entry = "bun tsc",
    priority = 20,
  },
  {
    id = "test",
    name = "test",
    language = "system",
    pass_filenames = false,
    entry = "bun test",
    priority = 30,
  },
]
